### PR TITLE
Implement optimized ticks

### PR DESCRIPTION
**Pull request by asinghvi17**
from PlotUtils.  While the function is not as fast as AutoLinearTicks, IMO it produces nicer looking ticks, especially at low size or resolution.

### CODE REVIEW

**Review by jkrumbiegel — COMMENTED** [review]
The existing tick locator (the one from matplotlib basically) is also an "optimized" one, so I'm not sure about the naming. Do you have visual examples for when it fails vs. the one you're proposing I put in? In the beginning I had that one but as you said took it out because it was quite slow, it made zooming stutter I think. So if I include it I would like a tangible benefit from that, otherwise the two are kind of redundant

**Comment by asinghvi17** [comment]
The main reason I included it was for static plots, where IMO the tick locations that this provides tend to be a little better, and it's less fiddly to change the number of ticks.  It's also good for geographical plots, because of the coordinate transformation throwing off the pixel estimation in the linear tick locator.  I totally agree that for zooming it doesn't make sense.

I'm probably not going to work on this for the rest of today, but I'll try to put up some visual examples tomorrow.

To be perfectly honest, I had no idea what else I would call this - any suggestions for the name are more than welcome.

EDIT: Just realized I could call them Wilkinson ticks as well...derp

**Comment by asinghvi17** [comment]
Well the first benefit is when there is 0 pixel width in one of the axes (when projecting using Foucault's projection, for example), and secondly the user interface is a little less complicated than simply giving an ideal pixel width.  Again, mostly meant for static plots - as you said, zooming will get slow with these ticks.

**Comment by jkrumbiegel** [comment]
I actually thought ideal pixel width is quite useful because that's what makes your plot look good no matter what size the axis is. What do I care how many ticks that turns out to give me? Although it's easy enough to offer the same thing just with number of ticks, that's what the pixel width gets converted to internally anyway

**Comment by jkrumbiegel** [comment]
What kind of output do you expect for an axis with 0 pixels width? I think right now the minimum is 2 with AutoLinearTicks but with 1 you can't interpret the plot anyway, and at 0 just hide the ticks?

**Comment by asinghvi17** [comment]
Well the problem is that it depends on the deformation, so if you take Foucault's transform as an example:
foucault
you'd probably need around 7 or 8 at least for the "fatter" section.  Thinner midsections would mean less ticks are needed.  

I agree that the auto-linear ticks work well in most situations, though - this is just a niche case, so that in case anyone wants to switch back to Plots.jl's ticks they can do that.

**Comment by jkrumbiegel** [comment]
I'm more inclined to make a CustomTicks version where you supply tick locator function and formatter, so you could put the wilkinson function in that. Rather than copy-pasting this code into the repo given that it's not *that* different from what already exists. A CustomTicks struct might be useful in many other cases, I'll think about it

**Comment by SimonDanisch** [comment]
Maybe put the function in PlotUtils? And @jkrumbiegel's fast version as well?

**Comment by jkrumbiegel** [comment]
I think this *is* the function from PlotUtils?

**Comment by asinghvi17** [comment]
Here's a case which I found annoying:

`AutoLinearTicks` x and y
Screen Shot 2020-02-16 at 10 06 24  43300AM

`WilkinsonTicks` x, `AutoLinearTicks` y
Screen Shot 2020-02-16 at 10 07 38  77000AM

`WilkinsonTicks` x and y
Screen Shot 2020-02-16 at 10 08 18  51800AM

Of course, it's possible to tune it, but I personally prefer these, and they're available through GeoMakie as well.

**Comment by jkrumbiegel** [comment]
I guess you'd get pretty much the same ticks with my function if you specified the number of ticks (which isn't exposed directly right now to be fair). Not to diss the Wilkinson function :) But I find it weird to have a tick locator function that doesn't include the width of the axis, because how is the density of lines on the axis not an important part of choosing ticks? With the current algorithm, multiple axes in different sizes look pleasantly similar in terms of grid density

**Pull request closed without merging**
